#!/bin/bash

echo "=== Supabase Edge Function 배포 가이드 ==="
echo ""
echo "1. Supabase CLI 설치 (이미 설치되어 있으면 건너뛰기)"
echo "   npm install -g supabase"
echo ""
echo "2. Supabase 프로젝트 연결"
echo "   supabase link --project-ref pkehcfbjotctvneordob"
echo ""
echo "3. 환경변수 설정 (Supabase 대시보드에서)"
echo "   https://app.supabase.com/project/pkehcfbjotctvneordob/functions/send-sms"
echo "   "
echo "   다음 환경변수를 설정하세요:"
echo "   PPURIO_USERNAME=nvr_7464463887"
echo "   PPURIO_API_KEY=d55f01a941947acd711702ede3f90b74fdda318a78ed26dbde193cceeb0af4ac"
echo "   SENDER_PHONE=01032453385"
echo ""
echo "4. Edge Function 배포"
echo "   supabase functions deploy send-sms"
echo ""
echo "5. 배포 확인"
echo "   supabase functions list"
echo ""
echo "=== 직접 배포 명령어 (순서대로 실행) ==="
echo ""
echo "# 1. 프로젝트 연결"
echo "supabase link --project-ref pkehcfbjotctvneordob"
echo ""
echo "# 2. Edge Function 배포"
echo "supabase functions deploy send-sms --no-verify-jwt"
echo ""
echo "# 3. 로그 확인"
echo "supabase functions logs send-sms --tail"